name: ESLint

on:
  push:
    branches:
      - main
      - stage
      - dev

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # You can change this to your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint  # Adjust the lint script command if needed
