name: ESLint

on:
  push:
    branches:
      - main
      - stage
      - dev

jobs:
  eslint:
    runs-on: ubuntu-latest

eslint-job:
  stage: test
  script:
    - cd eml
    - npm install --only-dev
    - node_modules/eslint/bin/eslint.js .
