# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

image: node

stages:
  - test

eslint-job:
  stage: test
  script:
    - cd eml
    - npm install --only-dev
    - node_modules/eslint/bin/eslint.js .

- name: Lint Action
uses: wearerequired/lint-action@v2.3.0
            
