name: Build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Use Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install React Native dependencies
        run: |
          npm install -g react-native-cli
          npm install

      - name: Build with Gradle
        run: ./android/gradlew assembleRelease