
name: CI 

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Expo CLI globally
        run: npm install -g expo-cli

      - name: Install EAS CLI globally
        run: npm install -g eas-cli

      - name: Install dependencies
        run: cd eml && npm install

      - name: Authenticate with Expo 
        env:
          PASSWORD: ${{ secrets.EXPO_PASSWORD }}
          
        run: expo login -u sofiiagran1 -p $PASSWORD

      - name: Extract Service Account JSON
        run: echo "${{ secrets.gcp_app_deployment_json_key }}" > service_account.json

      - name: Deploy to Play Store
        run: cd eml && eas submit --platform android --latest --non-interactive
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./service_account.json