
name: CI 

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - stage

jobs:

  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: List directories and files
        run: ls -al

      - name: Install dependencies
        run: cd eml && npm install

      - name: Run ESLint
        run: cd eml && npm run lint 

  test:
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: List directories and files
        run: ls -al

      - name: Install dependencies
        run: cd eml && npm install
        
      - name: Run Tests
        run: cd eml && npm run test 

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Expo CLI globally
        run: npm install -g expo-cli

      - name: Install EAS CLI globally
        run: npm install -g eas-cli

      - name: Install dependencies
        run: cd eml && npm install

      - name: Authenticate with Expo 
        env:
          PASSWORD: ${{ secrets.EXPO_PASSWORD }}
        run: expo login -u sofiiagran1 -p $PASSWORD

      - name: Publish
        run: cd eml && expo publish --non-interactive
      - name: Build Android
        run: cd eml && eas build -p android --profile production --non-interactive
      - name: Submit Android
        run: cd eml && eas submit -p android --latest --non-interactive
    


# Submit Android build using EAS with GCP service account key
eas submit --platform android --latest --service-account-key-path $GOOGLE_APPLICATION_CREDENTIALS --id $EAS_BUILD_ID --url $EAS_BUILD_URL --package $ANDROID_PACKAGE_NAME --track YOUR_TRACK --release-status YOUR_RELEASE_STATUS