name: Run Tests on Pull Request
on:
  pull_request:
    types:
      - opened

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Change to the Node.js version you need

      - name: List directories and files
        run: ls -al

      - name: Change to 'eml' directory
        run: cd eml && npm i

      - name: Install dependencies
        run: cd eml && npm run test
