name: Tests

on:
  workflow_run:
    workflows: ["Linting"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    needs: Linting.eslint
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: List directories and files
        run: ls -al

      - name: Install dependencies
        run: cd eml && npm install
        
      - name: Run Tests
        run: cd eml && npm run test

  independent:
    runs-on: ubuntu-latest
    steps:
      - name: Independent Job
        run: echo "This job runs independently"
