name: Run Tests on Pull Request and Branches
on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - dev
      - staging
      - main
jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20 
      
      - name: List directories and files
        run: ls -al

      - name: Install dependencies
        run: cd eml && npm install
        
      - name: Run Tests
        run: cd eml && npm run test  

      - name: Run ESLint
        run: cd eml && npm run lint 