name: Run Linting and Tests on Pull Request and Branches
on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - dev
      - staging
      - main
      - dev_linting

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Change to the Node.js version you need

      - name: List directories and files
        run: ls -al

      - name: Install dependencies
        run: cd eml && npm install

      - name: Run ESLint
        run: cd eml && npx eslint .

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Change to the Node.js version you need

      - name: List directories and files
        run: ls -al

      - name: Install dependencies
        run: cd eml && npm install

      - name: Run tests
        run: cd eml && npm run test
